Traceback (most recent call last):
  File "C:\Faks\5.Semestar\ppj\lab_3\SemantickiAnalizator.py", line 226, in <module>
    program()
  File "C:\Faks\5.Semestar\ppj\lab_3\SemantickiAnalizator.py", line 25, in program
    if retci[ind] == "<lista_naredbi>":
       ~~~~~^^^^^
IndexError: list index out of range
